### ISSUE TITLE
cordova.plugins is null

### ISSUE THREAD

**Issue by jjimenezlopez** [yurtaev/cordova-wifi-ssid#1]
Hi yurtaev,

I'm trying to use this plugin, but when I try to acces to `cordova.plugins.WiFiSSID`, the object `cordova.plugins` is null. I'm running my application in iOS emulator on a Mac, is it a problem?

Thanks!

Jose.

**Comment by yurtaev** [comment]
`CNCopyCurrentNetworkInfo` it doesn't work in simulator. Try in the device.

**Comment by jjimenezlopez** [comment]
Ok, thanks!
